spring:
  application:
    name: video-service

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://GrongoGlongo:123@cluster0.yrxsr.mongodb.net/video-displayer?appName=Cluster0}
      auto-index-creation: true


  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:video_user}
    password: ${RABBITMQ_PASSWORD:video_password}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/videos}

server:
  port: ${PORT:8082}

aws:
  cloudfront:
    key-pair-id: ${CLOUDFRONT_KEYPAIR_ID:K3BTW23UBI6NK8}
    path-to-private-key: "${CLOUDFRONT_PRIVATE_KEY_PATH:C:/Keys/video-keypair.pem}"
    domain: ${CLOUDFRONT_DOMAIN:d18tkusr9cdn5m.cloudfront.net}

  s3:
    bucket:
      region: ${S3_BUCKET_REGION:us-east-1}
      name: ${S3_BUCKET_NAME:video-displayer}


